bump_version: null
lint:
  files_exist:
  - CODE_OF_CONDUCT.md
  - assets/nf-core-nextflow-template_logo_light.png
  - docs/images/nf-core-nextflow-template_logo_light.png
  - docs/images/nf-core-nextflow-template_logo_dark.png
  - .github/ISSUE_TEMPLATE/config.yml
  - .github/workflows/awstest.yml
  - .github/workflows/awsfulltest.yml
  files_unchanged:
  - CODE_OF_CONDUCT.md
  - assets/nf-core-nextflow-template_logo_light.png
  - docs/images/nf-core-nextflow-template_logo_light.png
  - docs/images/nf-core-nextflow-template_logo_dark.png
  - .github/ISSUE_TEMPLATE/bug_report.yml
  multiqc_config:
  - report_comment
  nextflow_config:
  - manifest.name
  - manifest.homePage
  - validation.help.beforeText
  - validation.help.afterText
  - validation.summary.beforeText
  - validation.summary.afterText
nf_core_version: 3.0.2
org_path: null
repository_type: pipeline
template:
  author: genRAIT Inc.
  description: A template project for nextflow workflows that can be run on the genRAIT
    platform.
  force: true
  is_nfcore: false
  name: nextflow-template
  org: genrait
  outdir: ./genrait-nf-template
  skip_features: []
  version: 1.0.0dev
update: null
